# GitHub Actions workflow to build and deploy 11ty site to GitHub Pages
# Save this file as .github/workflows/deploy.yml

name: Deploy 11ty to GitHub Pages

on:
  push:
    branches:
      - main  # Set this to your default branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm ci
        working-directory: ./blog

      - name: Build site
        run: npx @11ty/eleventy
        working-directory: ./blog

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .blog/_site
          publish_branch: gh-pages
          force_orphan: true
